export const actions = [
	{ label: "Went outside", id: "outside" },
	{ label: "Pooped", id: "shit" },
	{ label: "Urinated", id: "piss" },
	{ label: "Vomited", id: "vom" },
	{ label: "Cried", id: "cry" },
	{ label: "Read quality material", id: "read" },
	{ label: "Finished a podcast", id: "pod" },
	{ label: "Creatively wrote", id: "write" },
	{ label: "Socialised", id: "social" },
	{ label: "Asked someone out", id: "askout" },
	{ label: "Been asked out", id: "askedout" },
	{ label: "Been on a romantic date", id: "date" },
	{ label: "Gamed", id: "game" },
	{ label: "Showered", id: "shower" },
	{ label: "Ate a substantial meal", id: "food" },
	{ label: "Took perscription drugs", id: "med" },
	{ label: "Took recreational drugs", id: "drug" },
	{ label: "Drank Alcohol", id: "booze" },
	{ label: "Had sex", id: "fuck" },
	{ label: "Solo sexed", id: "wank" }
].map((action) => Object.freeze(action));
